import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import TopMenu from '@/src/components/TopMenu';
import { authOptions } from './api/auth/[...nextauth]/route';
import { getServerSession } from 'next-auth';
import NextAuthProvider from '@/src/providers/NextAuthProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <ReduxProvider> */}
        <NextAuthProvider session={session}>
          <TopMenu />
          {children}
        </NextAuthProvider>
        
      </body>
    </html>
  );
}
