/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: KrStolorz (Krzysztof Stolorz) (https://sketchfab.com/KrStolorz)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/1997-fso-polonez-mr97-lp-1aaeb91beaaf4a9c9af944e72c1b93fe
Title: 1997 FSO Polonez MR97 (LP)
*/

'use client';

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { Mesh, BufferGeometry, Object3D } from 'three';
import { useEffect, useState } from 'react';
import { useFrame, useThree } from '@react-three/fiber';

export function Car({ carScene, ...props }: any) {
  const carRef: any = useRef<Object3D>(null);
  const { nodes, materials }: any = useGLTF(carScene);
  const [isPointerDown, setIsPointerDown] = useState(false);
  const { gl, viewport } = useThree();

  const lastX = useRef(0);
  const lastY = useRef(0);

  const handlePointerDown = (e: PointerEvent) => {
    setIsPointerDown(true);
    lastX.current = e.clientX;
    lastY.current = e.clientY;
  };

  const handlePointerUp = () => {
    setIsPointerDown(false);
  };

  const handlePointerMove = (e: PointerEvent) => {
    if (isPointerDown && carRef.current) {
      const dx = (e.clientX - lastX.current) / viewport.width;
      const dy = (e.clientY - lastY.current) / viewport.height;

      carRef.current.rotation.y += dx * Math.PI * 0.01;
      // carRef.current.rotation.x += dy * Math.PI * 0.01;

      lastX.current = e.clientX;
      // lastY.current = e.clientY;
    }
  };

  useEffect(() => {
    const canvas = gl.domElement;
    canvas.addEventListener('pointerdown', handlePointerDown);
    canvas.addEventListener('pointerup', handlePointerUp);
    canvas.addEventListener('pointermove', handlePointerMove);
    return () => {
      canvas.removeEventListener('pointerdown', handlePointerDown);
      canvas.removeEventListener('pointerup', handlePointerUp);
      canvas.removeEventListener('pointermove', handlePointerMove);
    };
  }, [gl, handlePointerDown, handlePointerMove, handlePointerUp]);

  return (
    <group ref={carRef} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chassis001_Vehicle_0.geometry}
        material={materials.Vehicle}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FLW001_Vehicle_0.geometry}
        material={materials.Vehicle}
        position={[0.866, 0.339, 1.331]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 9]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FRW001_Vehicle_0.geometry}
        material={materials.Vehicle}
        position={[-0.866, 0.339, 1.331]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 9]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.RRW001_Vehicle_0.geometry}
        material={materials.Vehicle}
        position={[-0.893, 0.339, -1.387]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.RLW001_Vehicle_0.geometry}
        material={materials.Vehicle}
        position={[0.893, 0.339, -1.387]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.License_Plate_Front001_Matricula_0.geometry}
        material={materials.Matricula}
        position={[0, 0.308, 2.138]}
        rotation={[-1.695, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.License_Plate_Back001_Matricula_0.geometry}
        material={materials.Matricula}
        position={[0, 0.826, -2.154]}
        rotation={[-1.537, 0, Math.PI]}
      />
    </group>
  );
}
