/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Idmental (https://sketchfab.com/idmental.id)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/parking-garage-free-download-5310b7d77b70427d936ec4253fff679c
Title: Parking garage [FREE DOWNLOAD]
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

import garageScene from '@/public/assets/garage.glb';

export function Garage({ ...props }): any {
  const { nodes, materials }: any = useGLTF(garageScene);
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, -0.001]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_walls_0.geometry}
              material={materials.walls}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_tiles001_0.geometry}
              material={materials['tiles.001']}
            />
          </group>
          <group
            position={[16103.865, -60.916, -18637.006]}
            rotation={[-Math.PI / 2, 0, 0.677]}
            scale={[533.018, 475.439, 533.018]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder_pipes_0.geometry}
              material={materials.pipes}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder_road_0.geometry}
              material={materials.road}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder_strips_0.geometry}
              material={materials.strips}
            />
          </group>
          <group
            position={[14825.754, 4108.268, -3962.248]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube008_pipes_0.geometry}
              material={materials.pipes}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube008_mechanic_0.geometry}
              material={materials.mechanic}
            />
          </group>
          <group
            position={[-2106.478, 5895.558, -31928.357]}
            rotation={[0, Math.PI / 2, 0]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube007_mechanic_0.geometry}
              material={materials.mechanic}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube007_notice_0.geometry}
              material={materials.notice}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder002_walls_0.geometry}
            material={materials.walls}
            position={[9698.969, 7686.632, -8621.884]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001_walls_0.geometry}
            material={materials.walls}
            position={[9698.969, 7686.632, -31952.93]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube002_tiles002_0.geometry}
            material={materials['tiles.002']}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vert001_pipes_0.geometry}
            material={materials.pipes}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder006_pipes_0.geometry}
            material={materials.pipes}
            position={[18675.285, 10131.945, -18563.813]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[100, 80.361, 100]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube001_mechanic_0.geometry}
            material={materials.mechanic}
            position={[4006.689, 5519.126, -10377.53]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube003_mechanic_0.geometry}
            material={materials.mechanic}
            position={[3466.432, 5519.126, -26026.617]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
            scale={[-100, 100, 100]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube004_mechanic_0.geometry}
            material={materials.mechanic}
            position={[3491.913, 9787.954, -18360.85]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube005_mechanic_0.geometry}
            material={materials.mechanic}
            position={[2593.119, 5519.126, -24446.662]}
            rotation={[-Math.PI / 2, 0, Math.PI / 2]}
            scale={[-100, 100, 100]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube006_mechanic_0.geometry}
            material={materials.mechanic}
            position={[3135.982, 5519.126, -11914.227]}
            rotation={[-Math.PI / 2, 0, Math.PI / 2]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube009_box_0.geometry}
            material={materials.material}
            position={[377.531, 810.185, -3755.198]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[47.309, 52.356, 67.783]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube010_box_0.geometry}
            material={materials.material}
            position={[377.531, 810.185, -5316.293]}
            rotation={[-Math.PI / 2, 0, 0.077]}
            scale={[47.309, 52.356, 67.783]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube011_box_0.geometry}
            material={materials.material}
            position={[296.8, 810.185, -6898.585]}
            rotation={[-Math.PI / 2, 0, -0.023]}
            scale={[47.309, 52.356, 67.783]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube012_box_0.geometry}
            material={materials.material}
            position={[296.8, 2346.82, -5880.059]}
            rotation={[-Math.PI / 2, 0, -0.023]}
            scale={[47.309, 52.356, 67.783]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube013_box_0.geometry}
            material={materials.material}
            position={[296.8, 2346.82, -4332.05]}
            rotation={[-Math.PI / 2, 0, -0.023]}
            scale={[47.309, 52.356, 67.783]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube014_box_0.geometry}
            material={materials.material}
            position={[296.8, 3882.878, -4022.401]}
            rotation={[-Math.PI / 2, 0, -0.023]}
            scale={[47.309, 52.356, 67.783]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube015_box_0.geometry}
            material={materials.material}
            position={[377.531, 810.185, -2252.798]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[47.309, 52.356, 67.783]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube016_box_0.geometry}
            material={materials.material}
            position={[296.8, 2346.82, -2586.91]}
            rotation={[-Math.PI / 2, 0, -0.023]}
            scale={[47.309, 52.356, 67.783]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube020_cone_0.geometry}
            material={materials.cone}
            position={[3588.579, 104.293, -13343.18]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={82.683}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube021_cone_0.geometry}
            material={materials.cone}
            position={[-63.628, 104.293, -8617.478]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={82.683}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vert_road_0.geometry}
            material={materials.road}
            position={[24443.275, 151.076, -11690.947]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube019_lamborghini_0.geometry}
            material={materials.lamborghini}
            position={[6948.096, 5732.923, 2347.911]}
            rotation={[-Math.PI, 0, -Math.PI / 2]}
            scale={114.709}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube022_cone_0.geometry}
            material={materials.cone}
            position={[3588.579, 104.293, -29406.619]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={82.683}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube023_cone_0.geometry}
            material={materials.cone}
            position={[3588.579, 384.702, -29406.619]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={82.683}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube024_cone_0.geometry}
            material={materials.cone}
            position={[3588.579, 599.423, -29406.619]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={82.683}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube025_cone_0.geometry}
            material={materials.cone}
            position={[3588.579, 814.619, -29406.619]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={82.683}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(garageScene);
